### ISSUE TITLE
Source code ETA?

### ISSUE THREAD

**Issue by wazowski78** [the-red-team/InstagramBot#1]
Hi,

I like a lot your work, I have tested the bot and works like a charm. Are you planning to release the source code?

Best regards.

**Comment by the-red-team** [comment]
I am undecided whether or not I want to release the code for this project

**Comment by wazowski78** [comment]
Thank you for your reply. Well, the main issue here is the login security, IG now do not allow the login from different places with the issue "Suspicious login notification", so I can not use it. I think the idea is great, but I can not use it with some extra hacks, like VPN server, etc...

So I would like to use it in my own server with a custom config. So, would you share a private copy of it with me?

Thank you very much.

**Comment by the-red-team** [comment]
I am working on having the bot use a list of proxies.

It will try to login to instagram from each proxy one at a time until it
hits a proxy without a login challenge

**Comment by the-red-team** [comment]
@wazowski78 I have updated the bot web service.
It now gets the location info of the user, picks a proxy with a geographical location close to the user, and uses it to login to Instagram. I have had several people test the new bot service and it works.

The only issue is having that one person who lives in an area that I don't have proxies for, but this doesn't happen often it seems

**Comment by wazowski78** [comment]
Nice approach in order to solve the location issue with login attempts. My main problem is that I need to run the bot in my own server, because of the amount of followers of my accounts I do not feel confidence sharing my IG credentials. So that's why I ask for the source code.
